### ISSUE TITLE
Dark Theme to help save monitors from burn in

### ISSUE THREAD

**Issue by ChaosBlades** [PartialVolume/shredos.2020.02#41]
Would be nice to change the current Blue/White theme to Black background with Light Gray text theme to help save monitors from burn in. The blue color if I remember correctly is the biggest contributor to burn in after white.

**Comment by PartialVolume** [comment]
@ChaosBlades According to [this](https://en.wikipedia.org/wiki/Image_persistence) article grey text on a white background may be preferable to grey text on black. I will probably add that option in the next release along with possibly powering off the display and reactivated by pressing a key as an additional option. White is better because to achieve black you apparently have to drive the LCD crystals to block light from the backlight. White is the relaxed state of the crystal.
